modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="optifinder"

version="1.15.2_HD_U_G1_pre30"

displayName="OptiFinder"

updateJSONURL="http://myurl.me/"

displayURL="https://www.nosiphus.com/minecraft/optifinder"

logoFile="examplemod.png"

credits="Nosiphus"

authors="Nosiphus"

description='''
A small mod that reminds users to add OptiFine to their modpacks.
'''

[[dependencies.optifinder]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.optifinder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
